In [ ]:
import winsound

tup1=(111,'alpha','beta','gamma',222)
print([*tup1])
for i in range(100000000000000000):
    print(i)

duration = 1000
freq = 440
winsound.Beep(freq, duration)

[111, 'alpha', 'beta', 'gamma', 222]


In [4]:
import torch
a=torch.tensor([
              [
                  [1, 5, 5, 2],
                  [9, -6, 2, 8],
                  [-3, 7, -9, 1]
              ],
 
              [
                  [-1, 7, -5, 2],
                  [9, 6, 2, 8],
                  [3, 7, 9, 1]
              ]])
b=torch.argmax(a,dim=1)
print(a)
print(a.shape)
print(b)
print(b.shape)

tensor([[[ 1,  5,  5,  2],
         [ 9, -6,  2,  8],
         [-3,  7, -9,  1]],

        [[-1,  7, -5,  2],
         [ 9,  6,  2,  8],
         [ 3,  7,  9,  1]]])
torch.Size([2, 3, 4])
tensor([[1, 2, 0, 1],
        [1, 0, 2, 1]])
torch.Size([2, 4])


In [7]:
import torch.nn.functional as F

a = torch.Tensor([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])

a_soft = F.softmax(a, dim=1)
print(a_soft)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]])


In [13]:
import random
i = random.choice((1, 2, 3, 4))
print(i)

4


In [22]:
class Solution:
    def twoSum(self, nums, target):
        self.nums = nums
        self.target = target
        a = []
        for i in nums:
            for j in nums[nums.index(i)+1 :]:
                if i + j == target:
                    a.extend([nums.index(i), nums.index(j)])
                    break
        return a
solution = Solution()
print(solution.twoSum([3, 2, 4], 6))

[1, 2]
